[project]
name = "huggingface-agent-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub>=0.29.1",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "python-dotenv>=1.0.1",
]
